import { AuthContextProvider } from "@/context/auth.context";
import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html >
  );
}
